### ISSUE TITLE
is the dataset open avaliable? 

### ISSUE THREAD

**Issue by raytrun** [ishaanshah/botanical-trees#1]
Excellent project. 
If the data is publicly available, it will be convenient to reproduce the results.

**Comment by ishaanshah** [comment]
Hi, sorry for the late reply. Unfortunately I can't make the dataset public. However, I have added the scripts that I have used for generating the dataset as well as some instruction about how it should be run. Please let me know if you face any issues while running it.

**Comment by raytrun** [comment]
Thank you for your reply. I think your scripts will be very helpful.
